workflows:
  sample-workflow:
    name: Build and Test Flutter App
    environment:
      flutter: 3.24.2 # Define la versión específica de Flutter
      xcode: latest # Versión de Xcode (si estás compilando para iOS)
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release # Para compilar la app iOS
